fx_version 'cerulean'
game { 'gta5' }
author 'BzZz'
description 'Bzzz - Bakery props'
version '1.1.0'



data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_restaurantmenu/bzzz_prop_restaurant_menu.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_smoking_pipe/bzzz_prop_smoking_pipe_a.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_stage_lights/bzzz_light_stage.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_weedbag/bzzz_weed_plastic_bag_package.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_gravestones/bzzz_gravestones.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_baby_cake/bzzz_electro_grill_kebab.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_baby_cake/bzzz_prop_cake_baby_001.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_bandanaflags/bzzz_bandana_flags.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_beehive_pack/bzzz_props_beehive_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_carpets/bzzz_carpetpack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_cigarpack/bzzz_effect_cigarpack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_counters/bzzz_counters_packages.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_easter/bzzz_event_easter_basket.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_decals/bzzz_normal_sign_decals.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_birthday_cake/bzzz_prop_cake_birthday_001.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_fighting_ring/bzzz_prop_fighting_ring.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_givegift/bzzz_prop_give_gift.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_lights_and_lamps/bzzz_dream_of_lights.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_lockpick/bzzz_props_lockpick_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_love_cake/bzzz_prop_cake_love_001.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_medicalprops/bzzz_medicalprops_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_lumberjack_wood/bzzz_lumberjack_wood_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_pizzabox/bzzz_package_pizzahut.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_alphabet_neon/bzzz_neon_alph.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_basket/bzzz_prop_shop_basket_a.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_custom_citysign/bzzz_prop_custom_citysign.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_custom_signs/bzzz_prop_carton_signs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_light_tube/bzzz_prop_light_tube_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_little_light/bzzz_light_little_color_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_neons/bzzz_neons_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_chalkboards/bzzz_chalkboards_package.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_bzzz_gympack/brum_bzzz_gym_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_custom_can/bzzz_custom_drink_cans.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/free/bzzz_new_snackprops/bzzz_new_snacks_package.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/free/bzzz_propshop/bzzz_prop_shop_items.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/free/bzzz_food_dessert/bzzz_food_dessert_a.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/free/bzzz_food_xmaspack/bzzz_food_xmas22.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/free/bzzz_icecream/bzzz_food_icecream_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_bakery/bzzz_food_bakery_props_package.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_beer_machine/bzzz_prop_beer_machine.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_bowlfood/bzzz_bowlfood_ytyp.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_chips/bzzz_prop_chips.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_cotton_candy/bzzz_candy_cotton.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_drinks/bzzz_drink_tup.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_fastfood/bzzz_food_fastfood_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_fruits/bzzz_fruits_foods.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_grillfood/bzzz_food_grill_bbq.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_juices/bzzz_drink_props_juicepack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_mixfood/bzzz_food_hotdog_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_pizzapack/bzzz_foodpack_pizzapack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_popcorn/bzzz_prop_popcorn_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_popsicles/bzzz_popsicle_package.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_restaurantfood/bzzz_restaurant_foodpack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_skewerpack/bzzz_food_skewerpack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_sugaryfood/bzzz_sugary_food.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/paid/bzzz_uwuprops/bzzz_uwuprops_package.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_blueprint/bzzz_prop_blueprint.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_convert_stripmenu/bzzz_convert_stripmenu.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_cross/bzzz_wood_cross.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_doghouse_convert/bzzz_doghouse_convert.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_electronics/bzzz_electronics_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_for_customers_lobster/bzzz_for_customers_lobster.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_mochito/bzzz_drink_mochito.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_prop_drugs_lean_cup/bzzz_prop_drugs_lean_cup.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_salad/bzzz_food_red_salad_a.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_smal3dprinter/bzzz_electro_prop_3dprinter_small.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_smokeprop/bzzz_smokeprop_package_joint.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/bzzz_xmas23_convert/bzzz_xmas23_convert_package.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles/discord/italy_food/bzzz_italy_food_rpack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_photoboxes/bzzz_photoboxes.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_casino_cake/bzzz_prop_cake_casino001.ytyp'