fx_version 'cerulean'
game { 'gta5' }

author 'BRUM & BzZz'
description 'BRUM & BzZz Gympack'
version '1.1.0'

files {
    'stream/*.ydr',
    'stream/*.ytyp',
    'stream/*.ymap',
    'stream/*.ytf'
}

data_file 'DLC_ITYP_REQUEST' 'stream/brum_bzzz_gym_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_alphabet_neon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_baby_cake.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_bandanaflags.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_beehive_pack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_basket.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_birthday_cake.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_carpets.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_casino_cake.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_chalkboards.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_cigarpack.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_counters.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_custom_can.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_custom_citysign.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_custom_signs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_decals.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_easter.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_fighting_ring.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_food_bundles.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_givegift.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_gravestones.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_kebab.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_light_tube.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_lights_and_lamps.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_little_light.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_lockpick.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_love_cake.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_lumberjack_wood.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_medicalprops.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_neons.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_photoboxes.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_pizzabox.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_restaurantmenu.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_smoking_pipe.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_stage_lights.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bzzz_weedbag.ytyp'
