    fx_version "cerulean"
games { 'gta5' }

author 'JuneBug'
description 'Envi-Pharmacy'
version '0.1.0'

this_is_a_map 'yes'

data_file 'DLC_ITYP_REQUEST' 'hw1_06_pharmcy_01'
data_file 'DLC_ITYP_REQUEST' 'pay-counter'
data_file 'DLC_ITYP_REQUEST' 'pharm-shell'
data_file 'DLC_ITYP_REQUEST' 'pharmacy-pic'
data_file 'DLC_ITYP_REQUEST' 'pharmacy-pic2'
data_file 'DLC_ITYP_REQUEST' 'pharmacy-pic3'
data_file 'DLC_ITYP_REQUEST' 'door-glass'
data_file 'DLC_ITYP_REQUEST' 'lights'
data_file 'DLC_ITYP_REQUEST' 'pharm-shelf'  
data_file 'DLC_ITYP_REQUEST' 'middle-sign'  
data_file 'DLC_ITYP_REQUEST' 'shelf-sign'
data_file 'DLC_ITYP_REQUEST' 'pills-rug'
data_file 'DLC_ITYP_REQUEST' 'pharm-posters'
data_file 'DLC_ITYP_REQUEST' 'poster-1'
data_file 'DLC_ITYP_REQUEST' 'poster-2'
data_file 'DLC_ITYP_REQUEST' 'poster-3'
data_file 'DLC_ITYP_REQUEST' 'poster-4'
data_file 'DLC_ITYP_REQUEST' 'poster-5'
data_file 'DLC_ITYP_REQUEST' 'poster-6'
data_file 'DLC_ITYP_REQUEST' 'poster-7'
data_file 'DLC_ITYP_REQUEST' 'poster-8'
data_file 'DLC_ITYP_REQUEST' 'poster-9'
data_file 'DLC_ITYP_REQUEST' 'poster-10'
data_file 'DLC_ITYP_REQUEST' 'poster-11'
data_file 'DLC_ITYP_REQUEST' 'poster-12'
data_file 'DLC_ITYP_REQUEST' 'pharm-shell-mirrorfloor' 
data_file 'DLC_ITYP_REQUEST' 'white-coat'
data_file 'DLC_ITYP_REQUEST' 'broken-desk'
data_file 'DLC_ITYP_REQUEST' 'envo-posters'
data_file 'DLC_ITYP_REQUEST' 'pharm-posters2'
data_file 'DLC_ITYP_REQUEST' 'pharm-posters3'
data_file 'DLC_ITYP_REQUEST' 'racks'
data_file 'DLC_ITYP_REQUEST' 'rug'
data_file 'DLC_ITYP_REQUEST' 'desk'
data_file 'DLC_ITYP_REQUEST' 'frame-1'
data_file 'DLC_ITYP_REQUEST' 'frame-2'
data_file 'DLC_ITYP_REQUEST' 'plug'
data_file 'DLC_ITYP_REQUEST' 'insurancesign'
dependency '/assetpacks'